spring.application.name=build-your-own-kafka

zookeeper.host=localhost
zookeeper.port=2181

kafka.log.base-dir=/tmp/kafka-logs
kafka.segment.size=1048576

broker.id=1
broker.host=localhost
broker.port=9092
broker.data-dir=data

kafka.bootstrap.host=localhost
kafka.bootstrap.port=9092
kafka.buffer.size=4096

kafka.producer.topic=orders
kafka.producer.default-partitions=3
kafka.producer.default-replication=2
kafka.producer.create-topic-if-not-exists=true
